// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivryhkkttofbzvthkgmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2cnloa2t0dG9mYnp2dGhrZ21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyNDE3OTgsImV4cCI6MjA3NzgxNzc5OH0.k0fOOgZg4VJz6mXEUZUn-k9G0-Y26rpR3aRcjwxUHbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});